### ISSUE TITLE
Providers.json not found

### ISSUE THREAD

**Issue by gopaldas958** [kozyol/AwesomeChatGPTBot#79]
**Unknown Issue**!

Log:
[Errno 2] No such file or directory: 'Accounts/621520367/providers.json'

This error come when I message to the bot.

**Comment by Kourva** [comment]
HI @gopaldas958, Thanks for reporting issue!
Oops, I forgot to handle new changes for users that already started the bot. Now you can re-clone the bot and use it.

Bot will send you prompt to restart the bot and make new account to add provider.json to your account!
